set(CMAKE_MODULES_DIR ${CMAKE_CURRENT_LIST_DIR})

include(Options)
include(CTest)
include(SetUp)
include(CodeFormatting)
include(Macro)
include(AddGoogleTest)
include(StaticAnalysis)
include(CodeCoverage)
